/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300064451
 */
public class Bank extends javax.swing.JFrame {

    /**
     * Creates new form Bank
     */
    public Bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDrozbits = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblGazoon = new javax.swing.JLabel();
        lblFrazoing = new javax.swing.JLabel();
        lblBlointoint = new javax.swing.JLabel();
        lblVrobits = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to the Bank of Zirboin");

        jLabel2.setText("Please enter your vrobit total below");

        jLabel3.setText("Drobzit");

        lbl2.setText("Clickwick");

        jLabel5.setText("Gazoontight");

        jLabel6.setText("Frazoint");

        jLabel7.setText("blointoint");

        jLabel8.setText("vrobits");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel4.setText("You Recieve:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVrobits)
                            .addComponent(lblBlointoint)
                            .addComponent(lblFrazoing)
                            .addComponent(lblGazoon)
                            .addComponent(lblClickwicks)
                            .addComponent(lblDrozbits))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(118, 118, 118))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrozbits, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClickwicks)
                    .addComponent(lbl2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGazoon)
                        .addGap(40, 40, 40)
                        .addComponent(lblFrazoing)
                        .addGap(39, 39, 39)
                        .addComponent(lblBlointoint)
                        .addGap(35, 35, 35)
                        .addComponent(lblVrobits)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
    //This variable is used to describe the amount of money the user inputed. It is updated throughout the process
    double money;
    
    //The program uses get text to initialize the money variable
    money = Double.parseDouble(txtMoney.getText());
    
    //Creates a variable which stores the return of the subroutine
    double Drozbits = Drobzits(money);
    
//sets the lbl to the value of Clickwicks
    lblDrozbits.setText(String.valueOf(Drozbits));
   //re-calculates the money after the subroutine
    money =(AfterDrozbits(Drozbits, money));
    
    
    //Creates a variable which stores the return of the subroutine
    double ClickWicks = Clickwicks(money);
    
    //sets the lbl to the value of ClickWicks
    lblClickwicks.setText(String.valueOf(ClickWicks));
    
    //re-calculates the money after the subroutine
    money =(AfterClickwicks(ClickWicks, money));
    
    //Creates a variable which stores the return of the subroutine
    double Gazzontight = GazoonTight(money);
    
    //sets the lbl to the value of gazoon
    lblGazoon.setText(String.valueOf(Gazzontight));
    
    //re-calculates the money after the subroutine
    money = (AfterGazoontight(Gazzontight, money));
    
    //Creates a variable which stores the return of the subroutine
    double Frazoint = Frazoint(money);
    
    //sets the lbl to the value of frazoint
    lblFrazoing.setText(String.valueOf(Frazoint));
    
    //re-calculates the money after the subroutine
    money = (AfterFrazoint(Frazoint,money));
    
    //Creates a variable which stores the return of the subroutine
    double blointoint = bloint(money);
    
    //sets the lbl to the value of blointoints
    lblBlointoint.setText(String.valueOf(blointoint));
    
    //re-calculates the money after the subroutine
    money = (Afterbloint(blointoint,money));
    
    //Creates a variable which stores the return of the subroutine
    double vrobits = vrobits(money);
    
    //sets the lbl to the value of vrobits
    lblVrobits.setText(String.valueOf(vrobits));
    
    //re-calculates the money after the subroutine
    money = (Aftervrobits(vrobits,money));
    
    
    }//GEN-LAST:event_btnCalculateActionPerformed
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the dribitz factor
    return: Factor
    */
    public static double Drobzits (double money){
        
        double factor = money/100000;
        factor = Math.floor(factor);
        
        return factor;
    }
    
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double AfterDrozbits(double factor, double total){
    
    total = total - (factor * 100000);
    return total;
    
    }
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the Clickwicks factor
    return: Factor
    */
    public static double Clickwicks (double money){
        double factor = money/50000;
        factor = Math.floor(factor);
        
        return factor;
    }
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double AfterClickwicks(double factor, double total){
    
    total = total - (factor * 50000);
    return total;
    }
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the Gazoontight factor
    return: Factor
    */
    public static double GazoonTight (double money){
        double factor = money/10000;
        factor = Math.floor(factor);
        
        return factor;
    }
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double AfterGazoontight(double factor, double total){
    
    total = total - (factor * 10000);
    return total;
    }
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the frazoint factor
    return: Factor
    */
    public static double Frazoint (double money){
        double factor = money/1000;
        factor = Math.floor(factor);
        
        return factor;
    }
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double AfterFrazoint(double factor, double total){
    
    total = total - (factor * 1000);
    return total;
    }
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the bloint factor
    return: Factor
    */
    public static double bloint(double money){
        double factor = money/500;
        factor = Math.floor(factor);
        
        return factor;
    }
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double Afterbloint(double factor, double total){
    
    total = total - (factor * 500);
    return total;
    }
    /*
    This subroutine takes the user inputed money and finds out the amount of times 100000 can be taken from the total and returns that number as the vrobits factor
    return: Factor
    */
    public static double vrobits(double money){
        double factor = money/1;
        factor = Math.floor(factor);
        
        return factor;
    }
    /*
    Takes the remaning money and subtracts the factor * the value of each coin to get an overall total after
    returns: total*/
    public static double Aftervrobits(double factor, double total){
        
    
    total = total - (factor * 1);
    return total;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblBlointoint;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblDrozbits;
    private javax.swing.JLabel lblFrazoing;
    private javax.swing.JLabel lblGazoon;
    private javax.swing.JLabel lblVrobits;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
