/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author westy
 */
public class StringMethods extends javax.swing.JFrame {

    /**
     * Creates new form StringMethods
     */
    public StringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLengthAns = new javax.swing.JLabel();
        btnLength = new javax.swing.JButton();
        txtLengthUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblCapitalUser = new javax.swing.JTextField();
        btnAllCaps = new javax.swing.JButton();
        lblCapitalAns = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt3rd = new javax.swing.JTextField();
        lbl3rdAns = new javax.swing.JLabel();
        btnLetter3 = new javax.swing.JButton();
        btnIdentical = new javax.swing.JButton();
        txtIdentical1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblIdenticalAns = new javax.swing.JLabel();
        btnLetterFound = new javax.swing.JButton();
        txtFound1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblfoundAns = new javax.swing.JLabel();
        btnLetter4To6 = new javax.swing.JButton();
        txt4to61 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lbl4to6Ans = new javax.swing.JLabel();
        btnReplaceA = new javax.swing.JButton();
        txtReplace = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblReplaceAns = new javax.swing.JLabel();
        txtIdentical2 = new javax.swing.JTextField();
        txtfound2 = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Super String Soft Ware");

        jLabel2.setText("Enter a String. The program will output the number of characters in the string");

        lblLengthAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLength.setText("Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter a String using lowercase letters. The Program will output the string in all capital letters");

        btnAllCaps.setText("AllCaps");
        btnAllCaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCapsActionPerformed(evt);
            }
        });

        lblCapitalAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("Enter a String, The program will output the character in the third spot");

        lbl3rdAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLetter3.setText("3rd Letter");
        btnLetter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetter3ActionPerformed(evt);
            }
        });

        btnIdentical.setText("Identical?");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter 2 strings. The program will output whether the 2 are identical");

        lblIdenticalAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLetterFound.setText("Letter Found?");
        btnLetterFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetterFoundActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter a string and a letter. The program will output whether or not the letter is found on the string");

        lblfoundAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLetter4To6.setText("Find Letters 4 to 6");
        btnLetter4To6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetter4To6ActionPerformed(evt);
            }
        });

        jLabel13.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6");

        lbl4to6Ans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnReplaceA.setText("Replaces \"a\"");
        btnReplaceA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceAActionPerformed(evt);
            }
        });

        jLabel15.setText("Enter a String that contains at least one \"a\" The programming will then replace all occurance of the letter \"a\" with the letter \"x\"");

        lblReplaceAns.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt4to61, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLetter4To6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtLengthUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapitalUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt3rd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAllCaps)
                            .addComponent(btnLetter3)
                            .addComponent(btnLength)
                            .addComponent(btnIdentical))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(btnReplaceA)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFound1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfound2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLetterFound)
                        .addGap(13, 13, 13)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdenticalAns)
                                    .addComponent(lbl3rdAns, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(lblCapitalAns, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblLengthAns, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lblfoundAns, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReplaceAns, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl4to6Ans, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLengthAns)
                    .addComponent(btnLength)
                    .addComponent(txtLengthUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapitalAns)
                    .addComponent(btnAllCaps)
                    .addComponent(lblCapitalUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3rdAns)
                    .addComponent(btnLetter3)
                    .addComponent(txt3rd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdenticalAns)
                    .addComponent(btnIdentical)
                    .addComponent(txtIdentical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentical2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfoundAns)
                    .addComponent(btnLetterFound)
                    .addComponent(txtFound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl4to6Ans)
                    .addComponent(btnLetter4To6)
                    .addComponent(txt4to61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReplaceAns)
                    .addComponent(btnReplaceA)
                    .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCapsActionPerformed
    //A value used to store the users input
    String UserInput;
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (lblCapitalUser.getText());
    
    //This line uses a string method to set all the letters to uppercase, and then outputs that information to the user 
    lblCapitalAns.setText (UserInput.toUpperCase());
    }//GEN-LAST:event_btnAllCapsActionPerformed

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
    //A value used to store the users input
    String UserInput;
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (txtLengthUser.getText());
    
   //This line uses a string method to find out the total characters in the users input, and then outputs that information to the user 
    lblLengthAns.setText(""+UserInput.length());
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnLetter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetter3ActionPerformed
    //A value used to store the users input
    String UserInput;
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (txt3rd.getText());
    
   //This line uses a string method to find out the 3 character in the users input, and then outputs that information to the user 
    lbl3rdAns.setText(""+UserInput.charAt(2));
    }//GEN-LAST:event_btnLetter3ActionPerformed

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
    //A value used to store the users input
    String UserInput;
    
    //A value used to store the users second input
    String UserInput2;
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (txtIdentical1.getText());
    
    //Gathers the users input from the text box and stores it as UserInput2
    UserInput2 = (txtIdentical2.getText());
   
    //This line uses a string method to find out whether the first input is identical to the second, and then outputs that information to the user 
   if (UserInput.equals (UserInput2)){
        lblIdenticalAns.setText("Identical");
   }
   //If the two entries are not identical
   else{
        lblIdenticalAns.setText("Not-Identical");
    }  
   
   
    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnLetterFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetterFoundActionPerformed
    //A value used to store the users input
    String UserInput;
    
    //A value used to store the users second input
    String UserInput2;
    
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (txtFound1.getText());
    
    //Gathers the users input from the text box and stores it as UserInput2
    UserInput2 = (txtfound2.getText());
    
   
    //This line uses a string method to find out whether the inputed word contains the Users chosen character
    if (UserInput.contains(UserInput2)){
        lblfoundAns.setText(UserInput2 + " is found in " + UserInput);
    }
    //outputs a message to the user if the chosen letter is not found
    else{
        lblfoundAns.setText(UserInput2 + " is not found in " + UserInput);
    }
   
    }//GEN-LAST:event_btnLetterFoundActionPerformed

    private void btnLetter4To6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetter4To6ActionPerformed
    //A value used to store the users input
    String UserInput;
   
    //gathers the users input from the text box and stores it as UserInput
    UserInput = (txt4to61.getText());
    
    //If the User enters a name with 8 or more characters the following will run
    if (UserInput.length() >= 8){
            lbl4to6Ans.setText (""+UserInput.charAt(3) + ""+UserInput.charAt(4) + ""+UserInput.charAt(5));
    }
    
    //If the User enters a name with 7 or less characters the following will run
    else{
        lbl4to6Ans.setText("Make sure it is least 8 characters");
    }
        
    
    
    }//GEN-LAST:event_btnLetter4To6ActionPerformed

    private void btnReplaceAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceAActionPerformed
     //A value used to store the users input
    String UserInput;
    
    //Gathers the users input from the text box and stores it as UserInput
    UserInput = (txtReplace.getText());
    
    //This line uses a string method to set all "a" to "x", and then outputs the replaced word to the user 
    lblReplaceAns.setText (UserInput.replace("a","x"));
    }//GEN-LAST:event_btnReplaceAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllCaps;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLetter3;
    private javax.swing.JButton btnLetter4To6;
    private javax.swing.JButton btnLetterFound;
    private javax.swing.JButton btnReplaceA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl3rdAns;
    private javax.swing.JLabel lbl4to6Ans;
    private javax.swing.JLabel lblCapitalAns;
    private javax.swing.JTextField lblCapitalUser;
    private javax.swing.JLabel lblIdenticalAns;
    private javax.swing.JLabel lblLengthAns;
    private javax.swing.JLabel lblReplaceAns;
    private javax.swing.JLabel lblfoundAns;
    private javax.swing.JTextField txt3rd;
    private javax.swing.JTextField txt4to61;
    private javax.swing.JTextField txtFound1;
    private javax.swing.JTextField txtIdentical1;
    private javax.swing.JTextField txtIdentical2;
    private javax.swing.JTextField txtLengthUser;
    private javax.swing.JTextField txtReplace;
    private javax.swing.JTextField txtfound2;
    // End of variables declaration//GEN-END:variables
}
