/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author westy
 */
public class MultipleChoiceQuiz extends javax.swing.JFrame {
    
//questionNum is an integer regarding the number of question the user is on
    double questionNum = 1;
    
//correctAnswers is an integer regarding the amount of correct answers the user has
    double correctAnswers = 0;
    
//incorrectAnswers an integer regarding the amount of incorrects answers the user has
    int incorrectAnswers = 0;
    
//score is the ratio of correct awensers, to total questions asked(gives an overall percentage)
    double score;
    
//UserInput is a string and takes memory of the users guess for each answer
    String UserInput;
    
   

    /**
     * Creates new form MultipleChoiceQuiz
     */
    public MultipleChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblQuestionNumb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        lblQuestionNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtGuess = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a-plus-symbol-pngrepo-com.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblQuestionNum.setText("Question: 1");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Multiple Choice Quiz");

        lblA.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblA.setText("a)  A leapord");

        lblC.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblC.setText("c)  A Gorilla");

        lblB.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblB.setText("b)  A cow");

        lblD.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblD.setText("d)  A Giraffe");

        lblCorrect.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrect.setText("Good Luck!");

        lblQuestion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("What Animal can Sleep Standing up, but can only dream whilst lying down?");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblBar.setForeground(new java.awt.Color(0, 204, 204));
        lblBar.setText("Progress Bar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblBar, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBar)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        txtGuess.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGuess)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGuess, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblB)
                            .addComponent(lblA)
                            .addComponent(lblC)
                            .addComponent(lblD))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblQuestionNum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuestionNum)
                            .addComponent(lblA))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblC)
                        .addGap(2, 2, 2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(718, 718, 718)
                .addComponent(lblQuestionNumb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQuestionNumb)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //this tells the program that once the user completes the 5 questions that the program should stop
        if (questionNum <= 5) {
            //gathers the users input(answer) from the text field for each question
            UserInput = (txtGuess.getText());

            //Tells the computer to only run this if its the first question
            if (questionNum == 1) {
                //tells the program that these are the awensers for the question, and provides the user with the points, or incorrect awenser
                if (UserInput.equals("B") || UserInput.equals("b")) {
                    correctAnswers = correctAnswers + 1;
                    lblMessage.setText("Correct!");
                }else{
                    incorrectAnswers = incorrectAnswers + 1;
                    lblMessage.setText("Incorrect!");
                }
                //changes the GUI to display the information for the second question
                lblQuestion.setText(String.valueOf("What is the scientific term for Wolf?"));
                lblA.setText(String.valueOf("a) Canis lupus "));
                lblB.setText(String.valueOf("b) Grey Wolves"));
                lblC.setText(String.valueOf("c) Canis latrans"));
                lblD.setText(String.valueOf("d) Vicugna pacos"));
                lblBar.setText(String.valueOf("|||||||||||||||||||||||||"));
            }
            //Tells the computer to only run this if its the second question
            if (questionNum == 2) {
                if (UserInput.equals("A") || UserInput.equals("a")) {
                    correctAnswers = correctAnswers + 1;
                    lblMessage.setText("Correct!");
                }else{
                    incorrectAnswers = incorrectAnswers + 1;
                    lblMessage.setText("Incorrect");
                }
                lblQuestion.setText(String.valueOf("How long can a Tarantula survive without food?"));
                lblA.setText (String.valueOf("a) 1 month"));
                lblB.setText (String.valueOf("b) 3 months"));
                lblC.setText (String.valueOf("c) 1 year"));
                lblD.setText (String.valueOf("d) 2 years"));
                lblBar.setText(String.valueOf("||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"));
            }
            //tells the computer to only run this if it's the third question
            if (questionNum == 3){
                if (UserInput.equals("D") || UserInput.equals("d")){
                    correctAnswers = correctAnswers + 1;
                    lblMessage.setText("correct");
                }else{
                    incorrectAnswers = incorrectAnswers + 1;
                    lblMessage.setText("Incorrect!");
                }
                lblQuestion.setText(String.valueOf("The Blue Whale is the largest animal in the world, but what is the largest whale sighting record to date?"));
                lblA.setText(String.valueOf("a) 98 feet, 400,000 lbs"));
                lblB.setText(String.valueOf("b) 102 feet, 415,000 lbs"));
                lblC.setText(String.valueOf("c) 72 feet, 340,000 lbs"));
                lblD.setText(String.valueOf("d) 120 feet, 440,00 lbs"));
                lblBar.setText(String.valueOf("||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"));
            }
            //tells the compouter to only run this if it's the forth question
            if (questionNum == 4){
                if (UserInput.equals("A") || UserInput.equals("a")){
                    correctAnswers = correctAnswers + 1;
                    lblMessage.setText("correct");
                }else{
                    incorrectAnswers = incorrectAnswers + 1;
                    lblMessage.setText("Incorrect!");
                }
                lblQuestion.setText(String.valueOf("How many hearts does a squid have?"));
                lblA.setText(String.valueOf("a) 4"));
                lblB.setText(String.valueOf("b) 5"));
                lblC.setText(String.valueOf("c) 2"));
                lblD.setText(String.valueOf("d) 3"));
                lblBar.setText(String.valueOf("|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"));
            }
            //tells the computer to only run this if it's the fifth question
            if (questionNum == 5){
                lblBar.setText(String.valueOf("||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"));
                if (UserInput.equals("D") || UserInput.equals("d")){
                    correctAnswers = correctAnswers + 1;
                    lblMessage.setText("correct");
                }else{
                    incorrectAnswers = incorrectAnswers + 1;
                    lblMessage.setText("Incorrect!");
                }}

                questionNum = questionNum + 1;
                lblQuestionNum.setText(String.valueOf("Question: " + questionNum));
                lblCorrect.setText(String.valueOf(correctAnswers + "/" + (questionNum -1)));

                score = correctAnswers/(questionNum -1);
                score = score*100;
                score = Math.round(score);
                

                //finds the results of the quiz, and displays the total score to the user
                if (questionNum ==6) {
                    lblQuestion.setText(String.valueOf(" "));
                    lblMessage.setText(String.valueOf(" "));
                    lblCorrect.setText(String.valueOf(" "));
                    lblQuestionNum.setText(String.valueOf(" "));
                    lblA.setText(String.valueOf("Congrats you completed the quiz!"));
                    lblB.setText(String.valueOf("Correct Answers: "  + correctAnswers));
                    lblC.setText(String.valueOf("Incorrect Answers: " + incorrectAnswers));

                    //displays the score for people with a grade above or equal to 3
                    if (correctAnswers >= 3)
                    lblQuestion.setText(String.valueOf("Yay you passed the quiz:)"));
                    lblD.setText(String.valueOf("You achieved a score of " + score + "%"));

                    //displays the score for people with a grade below or equal to 2
                    if (correctAnswers <= 2 ){
                        lblQuestion.setText(String.valueOf("Sorry, you did not pass the quiz"));
                        lblD.setText(String.valueOf("You achieved a score of " + score + "%"));}

                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MultipleChoiceQuiz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestionNum;
    private javax.swing.JLabel lblQuestionNumb;
    private javax.swing.JTextField txtGuess;
    // End of variables declaration//GEN-END:variables
}
