public class DtoBtoH extends javax.swing.JFrame {


public DtoBtoH() {
        initComponents();
    }
/*
This method converts the given decimal values into Binary values
Needs: int input
Outputs: Output
*/
public void DtoB (int input){

    //creates a string value and stores initializes it
    String Output = "";
    //creates the binary array which stores the vlaues calculted in the process
    int binary[] = new int[40];
    //creates a predetermined value for i
    int i = 0;
    
    //Creates a while loop which runs as long as the input does not equal 0
    while(input != 0){
        //stores each value every time the loop runs
        binary[i] = input%2;
        //divides the input value by 2
        input = input/2;
        //increases the value of i each time
        i++;
    }
    //creates a for loop which runs until value J is equal to or less than 0
    for (int j = i - 1; j >= 0; j--){
        //sets the output value
        Output = Output + binary[j];
    }
    //outputs the final value to the user
    lblDtoBAns.setText(Output);
    }
/*
This method converts the given binary values into decimal values
Needs: int input
Outputs: decimal
*/   
 public void BtoD (int input){
   //creates a preditermined value for i(set as 0)
    int i = 0;
     //creates a preditermined value for decimal(set as 0)
    int decimal = 0;
    //creates a while loop which runs as long as input doesnot equal 0
    while(input != 0){
          //creates and sets the remainder value
          int remainder = input%10;
          //gives the decimal variable and updated value 
          decimal += remainder*Math.pow(2, i);
          //divides the input by 10
          input = input/10;
          //increases the value of i by 1
          i++;
       }
    //outputs the decimal value to the user
    lblBtoDAns.setText(String.valueOf(decimal));
    
    }
/*
This method converts the given decimal values into hexidecimal values
Needs: int input
Outputs: reamindingnumber
*/ 
public void DtoH (int input){
    // creates a varibale to store the remainder
     int remainder;
        
     // creates a variable to store the final string(set to "")
     String remaindingnumber=""; 
 
     // Sets the didgets found in the hexidecimal number system
     char hexValues[]={'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F'};
 
     //creates a for loop which runs until the input value is less than 0
     while(input>0)
     {
       //sets the remainder value
       remainder=input%16; 
       //sets the value of the remainding number equal to hexValues[remainder]+remaindingnumber; 
       remaindingnumber=hexValues[remainder]+remaindingnumber; 
       //divides the input number by 16
       input=input/16;
     }
     //outputs the  remaindingnumber to the user
     lblDtoHAns.setText(remaindingnumber);
}
/*
This method converts the given hexidecimal values into decimal values
Needs: int input
Outputs: Output
*/ 
public void HtoD (String input){
    //creates a string variable to store the different hexvalues
    String hexValues = "0123456789ABCDEF";  
    
        //sets the userinput to upper case letters
	input = input.toUpperCase();  
        //creates a variable for num and sets it equal to 0
	int num = 0;  
        //creates a for loop to run until the i value is < the input values length
	for (int i = 0; i < input.length(); i++)  
	{  
            //creates a char value to gather the inputed char at each location
            char ch = input.charAt(i);  
                //creates an integer value to store the values
		int n = hexValues.indexOf(ch);  
                //num is times by 16 and the letter(value) is added
		num = 16*num + n;  
	}  
        //outputs the num to the user
       lblHtoDAns.setText(String.valueOf(num));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HtoD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnBtoD = new javax.swing.JButton();
        DtoB = new javax.swing.JButton();
        lblBtoDAns = new javax.swing.JLabel();
        lblDtoBAns = new javax.swing.JLabel();
        lblDtoHAns = new javax.swing.JLabel();
        lblHtoDAns = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDtoB = new javax.swing.JTextField();
        txtBtoD = new javax.swing.JTextField();
        txtDtoH = new javax.swing.JTextField();
        txtHtoD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter a decimal number(int)");

        jLabel2.setText("Enter a Binary Number");

        jLabel3.setText("Please enter a Decimal number(Posotive int)");

        jLabel4.setText("Enter a Hexadecimal value");

        HtoD.setText("Convert");
        HtoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HtoDActionPerformed(evt);
            }
        });

        jButton2.setText("Convert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnBtoD.setText("Convert");
        BtnBtoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBtoDActionPerformed(evt);
            }
        });

        DtoB.setText("Convert");
        DtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtoBActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Number System");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Decimal and binary converions");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Hexadecimal and Decimal conversions");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel8.setText("rememeber only 1, and 0's");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHtoD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDtoH))
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDtoB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(txtBtoD, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DtoB)
                            .addComponent(BtnBtoD)
                            .addComponent(jButton2)
                            .addComponent(HtoD))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHtoDAns)
                            .addComponent(lblDtoHAns)
                            .addComponent(lblDtoBAns)
                            .addComponent(lblBtoDAns))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 274, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DtoB)
                    .addComponent(lblDtoBAns)
                    .addComponent(txtDtoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BtnBtoD)
                    .addComponent(lblBtoDAns)
                    .addComponent(txtBtoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2)
                    .addComponent(lblDtoHAns)
                    .addComponent(txtDtoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HtoD)
                    .addComponent(lblHtoDAns)
                    .addComponent(jLabel4)
                    .addComponent(txtHtoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtoBActionPerformed
    //creates a varible and stores the userinput
    int Userinput = Integer.parseInt(txtDtoB.getText());
    //tells the following subroutine to run using the user inputed value
    DtoB(Userinput);
    }//GEN-LAST:event_DtoBActionPerformed

    private void BtnBtoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBtoDActionPerformed
    //creates a varible and stores the userinput
    int Userinput = Integer.parseInt(txtBtoD.getText());
    //tells the following subroutine to run using the user inputed value
     BtoD(Userinput);
    
    }//GEN-LAST:event_BtnBtoDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //creates a varible and stores the userinput
    int Userinput = Integer.parseInt(txtDtoH.getText());
    //tells the following subroutine to run using the user inputed value
     DtoH(Userinput);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void HtoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HtoDActionPerformed
    //creates a varible and stores the userinput
    String Userinput = (txtHtoD.getText());
    //tells the following subroutine to run using the user inputed value
    HtoD(Userinput);
    }//GEN-LAST:event_HtoDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DtoBtoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DtoBtoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DtoBtoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DtoBtoH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DtoBtoH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBtoD;
    private javax.swing.JButton DtoB;
    private javax.swing.JButton HtoD;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBtoDAns;
    private javax.swing.JLabel lblDtoBAns;
    private javax.swing.JLabel lblDtoHAns;
    private javax.swing.JLabel lblHtoDAns;
    private javax.swing.JTextField txtBtoD;
    private javax.swing.JTextField txtDtoB;
    private javax.swing.JTextField txtDtoH;
    private javax.swing.JTextField txtHtoD;
    // End of variables declaration//GEN-END:variables
}
