/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s300064451
 */

public class ScienceGame extends javax.swing.JFrame {
//Creates a preset variable for button presses, set at 17
int btnpresses = 1;

//Creates a variable for age to allow the original program to commence, gets updated throughout
int age = 1000000;

// Creates a string for the word which is completely randomized in the subroutine
String Word = (QuestionEasy());

//Creates a character which is randomized each time the program is run
char letter = Letter(Word);
    /**
     * Creates new form ScienceGame
     */
    public ScienceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        txtAnswer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cubes.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Spelling Game");

        jLabel3.setText("Please enter your age Below!");

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Try your best to spell this Word!");

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        txtAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer.setText("Put the Missing Letter Here!");
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });

        jButton1.setText("Ready!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblHint.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblHint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHint.setText("Help");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnConfirm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1))
                    .addComponent(lblHint, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
    //Creates an input variable to store the users responce
    String input; 
    
    //Creates a second variable which is equal to the first character in the players responce
    char userChoice;
    
    
    //Gather and stores the users input under input    
    input = (""+txtAnswer.getText());
    
    //Finds the first character of the users input
    userChoice = input.charAt(0);
    txtAnswer.setText("");
        
    //checks if the users entry and correct answer are equal in the subroutine permitts it through
        if (CheckAnswer(userChoice, letter)==true){
            
            //outputs congratulatory message to user
            lblMessage.setText("Correct");
            }
        
        else {
            //outputs message to user
            lblMessage.setText("Incorrect");  
           }
          
            
            
                 
        //tells the delay subroutine to run  
        wait(500);
        
        //Creates a switch statement check for the words length and based on the length goes to different cases
        switch (Word.length()) {
            case 1:
                //sets the string to nothing
                lbl4.setText(" ");
                
                break;
            case 2:
                //sets the string to nothing
                lbl4.setText(" ");
                lbl5.setText(" ");
                
                break;
            case 3:
                //sets the string to nothing
                lbl3.setText(" ");
                lbl4.setText(" ");
                lbl5.setText(" ");
                
                break;
            case 4:
                //sets the string to nothing
                lbl3.setText(" ");
                lbl4.setText(" ");
                lbl5.setText(" ");
                lbl6.setText(" ");
               
                break;
            case 5:
                //sets the string to nothing
                lbl2.setText(" ");
                lbl3.setText(" ");
                lbl4.setText(" ");
                lbl5.setText(" ");
                lbl6.setText(" ");
                
                break;
            
            default:
                 break;
        }
        //creates array to store values as strings
        String []output1 = new String [6];
        
        
        //Creates a switch statement check for the words length and based on the length goes to different cases
        switch (Word.length()) {
            case 1:
                //Sets the lbl to the specific character
                output1 [0] = String.valueOf(Word.charAt(0));
                lbl5.setText (output1[0]);
                
                break;
                
            case 2:
                //Sets the lbl to the specific character
                output1 [0] = String.valueOf(Word.charAt(0));
                lbl4.setText (output1[0]);
                output1 [1] = String.valueOf(Word.charAt(1));
                lbl5.setText (output1[1]);
                
                
                break;
                
            case 3:
                //Sets the lbl to the specific character
                output1 [0] = String.valueOf(Word.charAt(0));
                lbl3.setText (output1[0]);
                output1 [1] = String.valueOf(Word.charAt(1));
                lbl4.setText (output1[1]);
                output1 [2] = String.valueOf(Word.charAt(2));
                lbl5.setText (output1[2]);
                
                break;
                
            case 4:
                //Sets the lbl to the specific character
                output1 [0] = String.valueOf(Word.charAt(0));
                lbl3.setText (output1[0]);
                output1 [1] = String.valueOf(Word.charAt(1));
                lbl4.setText (output1[1]);
                output1 [2] = String.valueOf(Word.charAt(2));
                lbl5.setText (output1[2]);
                output1 [3] = String.valueOf(Word.charAt(3));
                lbl6.setText (output1[3]);
               
                break;
            
            case 5:
                //Sets the lbl to the specific character
                output1 [0] = String.valueOf(Word.charAt(0));
                lbl2.setText (output1[0]);
                output1 [1] = String.valueOf(Word.charAt(1));
                lbl3.setText (output1[1]);
                output1 [2] = String.valueOf(Word.charAt(2));
                lbl4.setText (output1[2]);
                output1 [3] = String.valueOf(Word.charAt(3));
                lbl2.setText (output1[4]);
                output1 [4] = String.valueOf(Word.charAt(4));
                
                break;
            
            default:
                 break;
        
        
       
          
       
       
          }
      
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //forces the program to begin immidetly
    if (btnpresses == 1){
   
        //Creates a variable to store the value of the randomized word combination
        String Random = Randomize1(Word, letter); 
    
    //Gives hints to the user depending on which animal they must try to spell
    if (Word.equals ("dog")){
        lblHint.setText("I'm a memeber of the wolf family, and many people keep me as pets");
    }
    
    //Gives hints to the user depending on which animal they must try to spell
    if (Word.equals ("cat")){
    lblHint.setText("I'm in the same family as lions, and many people keep me as pets");
    }
    
    //Gives hints to the user depending on which animal they must try to spell
    if (Word.equals ("squid")){
    lblHint.setText("I have 10 limbs, Some of my popular ancesters were known for thier 'giant' sizes");
    }
    
    //Gather the users input for the age
    age = Integer.parseInt(txtAge.getText());
        
        //if the users age is under 6 the following will run
        if ((age <= 6) && (age >= 1)){
            
            //Sets the text to nothing for users ease
           lblMessage.setText(" ");
           
            //Creates array to store entries
           String [] output = new String [6];
        
        //Creates a switch statement which check the stored random values length and organizes them based on length
        switch (Random.length()) {
            case 1:
                //Sets the lbl to the specific character
                output [0] = String.valueOf(Random.charAt(0));
                lbl5.setText (output[0]);
                
                break;
                
            case 2:
                //Sets the lbl to the specific character
                output [0] = String.valueOf(Random.charAt(0));
                lbl4.setText (output[0]);
                output [1] = String.valueOf(Random.charAt(1));
                lbl5.setText (output[1]);
                
                
                break;
                
            case 3:
                //Sets the lbl to the specific character
                output [0] = String.valueOf(Random.charAt(0));
                lbl3.setText (output[0]);
                output [1] = String.valueOf(Random.charAt(1));
                lbl4.setText (output[1]);
                output [2] = String.valueOf(Random.charAt(2));
                lbl5.setText (output[2]);
                
                break;
                
            case 4:
                //Sets the lbl to the specific character
                output [0] = String.valueOf(Random.charAt(0));
                lbl3.setText (output[0]);
                output [1] = String.valueOf(Random.charAt(1));
                lbl4.setText (output[1]);
                output [2] = String.valueOf(Random.charAt(2));
                lbl5.setText (output[2]);
                output [3] = String.valueOf(Random.charAt(3));
                lbl6.setText (output[3]);
               
                break;
            
            case 5:
                //Sets the lbl to the specific character
                output [0] = String.valueOf(Random.charAt(0));
                lbl2.setText (output[0]);
                output [1] = String.valueOf(Random.charAt(1));
                lbl3.setText (output[1]);
                output [2] = String.valueOf(Random.charAt(2));
                lbl4.setText (output[2]);
                output [3] = String.valueOf(Random.charAt(3));
                lbl2.setText (output[4]);
                output [4] = String.valueOf(Random.charAt(4));
                
                break;
            
            default:
                 break;
                }
        }   
        
        //if the user age is over 6 a message will run to the user
        else {
            
        lblMessage.setText("This is designed for people between the age 1 and 6");
        
            }
        //Sets text to nothing for users ease
        txtAnswer.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    Subroutine which randomizes a number and based on the result choses the word that will be used
    returns: word1
    */
    public static String QuestionEasy() {
       //Creates a variable which will store the randomized value
        int randomnum;
       
       //randomizes value between 1 and 3
       randomnum = (int)Math.round(Math.random()*2+1);
        
       //if the randomnum equals 1 the following will run
       if (randomnum == 1){
        String Word1 = "dog";
        
        
        return Word1;
        }
        
       //if the randomnum equals 1 the following will run
        if (randomnum == 2){
        //creates string variable Word1
            String Word1 = "cat";
        
        
        return Word1;
        }
        
        //if the randomnum equals 1 the following will run
        if (randomnum == 3){
        //creates string variable Word1
        String Word1 = "squid";
        
        return Word1;
        }
       
        else {
        return "no";
        }   
    }
    
    /*
    Creates a subroutine to randomly chose a letter to remove and replace for the user to guess
    return: letter
    */
    public static char Letter(String Word){
        
    //Creates char variable letter    
    char letter;
    //creates int variable Randomize
    int Randomize;
    
    //Randomizes to get a random integer using the word length as a restriction
    Randomize = (int)Math.round(Math.random()*(Word.length()-1));
    //Choses the letter at the randomly chosen location
    letter = Word.charAt(Randomize);
    return letter;
    
    
    }
    
    /*
    Creates a subroutine to replace the randomly chosen word with a substitute for the user to guess 
    return: word
    */
    public static String Randomize1 (String Word, char letter){
    //Makes variable word equal to the given
    String word = Word;
    
    //Tells the word to replace the randomly generated letter with _.
    word = word.replace(String.valueOf(letter),"_");
    //returns the word
    return word;
    }
    
    /*
    Creates a boolean subroutine to compare the user responce and the correct answer
    result: Yesno(bool)
    */
    public static boolean CheckAnswer (char userChoice  , char letter){
    //creates boolean variable which stores whether the user was correct or not
        boolean yesno; 
            
        //if the letter is the same as the users input then the bool value will be set to true and returned as so
            if (letter == (userChoice)){
                
                yesno = true;
            }
            
            //if not then the bool value will be set to false and returned
            else{
                yesno = false;
            }
    return yesno;
            }
    
      public static void wait(int ms){
        try
        {
            //Creates a delay
           Thread.sleep(ms); 
        }
        catch(InterruptedException ex)
        {
           //ends the delay
           Thread.currentThread().interrupt();
        }
    }

    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScienceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
