/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 
 * @author s300064451
 */
public class Stattracker extends javax.swing.JFrame {
    int btnpresses = 0;

    /**
     * Creates new form StatTracker
     */
    public Stattracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBaseball = new javax.swing.JButton();
        btnHockey = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txtGoals = new javax.swing.JTextField();
        txtAssists = new javax.swing.JTextField();
        txtPlus = new javax.swing.JTextField();
        txtMinus = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        txtFavouritePlayer = new javax.swing.JTextField();
        lblProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sports Stat Tracker");

        btnBaseball.setText("Baseball");
        btnBaseball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaseballActionPerformed(evt);
            }
        });

        btnHockey.setText("Hockey");
        btnHockey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHockeyActionPerformed(evt);
            }
        });

        lbl1.setForeground(new java.awt.Color(255, 255, 255));

        lbl2.setForeground(new java.awt.Color(255, 255, 255));

        lbl3.setForeground(new java.awt.Color(255, 255, 255));

        lbl4.setForeground(new java.awt.Color(255, 255, 255));

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("Welcome! Please choose a Sport");

        lblPlayer.setForeground(new java.awt.Color(255, 255, 255));

        txtFavouritePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFavouritePlayerActionPerformed(evt);
            }
        });

        lblProgress.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblProgress.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFavouritePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnBaseball, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(btnHockey))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAssists, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(txtMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(268, 268, 268))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(462, 462, 462))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMessage)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163)))
                .addComponent(lblProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMessage)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaseball)
                    .addComponent(btnHockey))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFavouritePlayer)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAssists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHockeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHockeyActionPerformed
    
    //A string value to store the player the user has chosen
    String player;
    
    //the that stores the value of the users entry by adding stat [1][2]
    double points;
    
    //a variable that stores the value of the users entry by dividing the points by game
    double ppg;
    
    //A constant that takes note of the total games played
    final int GP = 5;
    
//creates an array that stores the data which the user has entered    
    int [] stat = new int [4];    
    
          
            //this code will run if the btn presses value is equal to 1
            if (btnpresses == 0){
                btnHockey.setText("Select"); 
                btnBaseball.setText("");
                lblMessage.setText("You have chosen Hockey");
                lblPlayer.setText("You have chosen Hockey, Please enter your favourite player");
           }
            //this code will run if the btn presses value is equal to 1
            else if (btnpresses == 1){
                player = txtFavouritePlayer.getText();
                lblPlayer.setText(player);
                txtFavouritePlayer.setText("");
                lbl1.setText("Total Goals in last 5 games: ");
            }
            
            //this code will run if the btn presses value is equal to 2
            else if (btnpresses == 2){
                lbl2.setText("Total assists in the last 5 games: ");
            }

            //this code will run if the btn presses value is equal to 3
            else if (btnpresses == 3) {
                lbl3.setText("How many goals for was your player on for: ");
            }

            //this code will run if the btn presses value is equal to 4
            else if (btnpresses == 4) {
                lbl4.setText("How many goals against was your player on for: ");
                btnHockey.setText("See Stats");
            }
            
            //this code will run if the btn presses value is equal to 5
            else if (btnpresses == 5){
                
                //gathers the users information from each of the text boxes
                stat [0] = Integer.parseInt (txtGoals.getText());
                stat [1] = Integer.parseInt (txtAssists.getText());
                stat [2] = Integer.parseInt (txtPlus.getText());
                stat [3] = Integer.parseInt (txtMinus.getText());
                points = stat [0] + stat [1];
                ppg = points/GP;
            
                //outputs the results to the user
                lbl1.setText("Total points in last " + GP + " Games Played:");
                txtGoals.setText(String.valueOf(points));
                lbl2.setText("Points per game average:");
                txtAssists.setText(String.valueOf (ppg) + "pts");
                lbl3.setText("Plus/Minus:");
                txtPlus.setText(String.valueOf(stat [2]) + "/" + String.valueOf(stat[3]));
                
                //outputs a message to the user if the player has bad results
                if (points <= 2){
                    lbl4.setText("Wow,your player badly this week");
             }
                
                //outputs a message to the user if the player has good results
                else 
                    lbl4.setText("Wow your player played Very good this week!");
            
            }
    btnpresses = btnpresses+1;
    
    //creates a for loop which creates a progress bar by capping its maximum at 1 below the btnpresses value
    for (int i = 5; i >= (btnpresses - 1); i = i-1){
    lblProgress.setText(i + "/5");
    }
    
    }//GEN-LAST:event_btnHockeyActionPerformed

    private void btnBaseballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaseballActionPerformed
       
       //A string of variable that stores the users chosen player
       String Player;
       
       //a double value that stores the users values stat [3/1]
       double OBP;
       
       //a double value that stores the users values stat [0/1]
       double HRP;
       
       //a double value that stores the users values stat [2/1]
       double KOP;
       
       //creates an array to store the users entry's as doubles      
       double [] stat = new double [4];    
            
            //this code will run if the btn presses value is equal to 0
            if (btnpresses == 0){
            btnHockey.setText(""); 
            btnBaseball.setText("Select");
            lblMessage.setText("You have chosen Baseball");
            lblPlayer.setText("You have chosen Baseball, Please enter your favourite player");
           }
            
            //this code will run if the btn presses value is equal to 1
            else if (btnpresses == 1){
                Player = txtFavouritePlayer.getText();
                lblPlayer.setText(Player);
                txtFavouritePlayer.setText("");
                lbl1.setText("Total Homeruns in last 5 games: ");
            }
            
            //this code will run if the btn presses value is equal to 2
            else if (btnpresses == 2){
                lbl2.setText("Total at bats in the last 5 games: ");
            }

            //this code will run if the btn presses value is equal to 3
            else if (btnpresses == 3) {
                lbl3.setText("Total times your player has struken out: ");
            }

            //this code will run if the btn presses value is equal to 4
            else if (btnpresses == 4) {
                lbl4.setText("Total hits in past 5 games ");
                btnBaseball.setText("See Stats");
            }
            
            //this code will run if the btn presses value is equal to 5
            else if (btnpresses == 5){
                //gathers the users information from each of the text boxes
                stat [0] = Integer.parseInt (txtGoals.getText());
                stat [1] = Integer.parseInt (txtAssists.getText());
                stat [2] = Integer.parseInt (txtPlus.getText());
                stat [3] = Integer.parseInt (txtMinus.getText());
            
                //calculates the value of variable OBM
                OBP = stat [3] / stat [1];
                OBP = OBP *100;
                OBP = Math.round(OBP);
            
                //calculates the value of variable HRP
                HRP = stat [0] / stat [1];
                HRP = HRP *100;
                HRP = Math.round(HRP);
            
                //calculates the value of variable KOP
                KOP = stat [2] / stat [1];
                KOP = KOP*100;
                KOP = Math.round(KOP);
            
                //outputs the results to the user
                lbl1.setText("Your player has an on base percentage of:");
                txtGoals.setText(String.valueOf(OBP) + "%");
                lbl2.setText("Home run Percentage");
                txtAssists.setText(String.valueOf (HRP) + "%");
                lbl3.setText("Strucken out percentage:");
                txtPlus.setText(String.valueOf(KOP) + "%");
            
            }
    btnpresses = btnpresses+1;
       
    //creates a for loop which creates a progress bar by capping its maximum at 1 below the btnpresses value
    for (int i = 5; i >= (btnpresses - 1); i = i-1){
    lblProgress.setText(i + "/5");
    }
       
       
    }//GEN-LAST:event_btnBaseballActionPerformed

    private void txtFavouritePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFavouritePlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFavouritePlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stattracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stattracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stattracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stattracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stattracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaseball;
    private javax.swing.JButton btnHockey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JTextField txtAssists;
    private javax.swing.JTextField txtFavouritePlayer;
    private javax.swing.JTextField txtGoals;
    private javax.swing.JTextField txtMinus;
    private javax.swing.JTextField txtPlus;
    // End of variables declaration//GEN-END:variables
}
